module.exports = {

  'parser': 'babel-eslint',

  'env': {
    'node': true,
    'browser': true,
  },

  'globals': {
    'escape': true,
    'unescape': true,
  },

  'plugins': [
    'react',
  ],

  'rules': {

    // -----------------------------------------------------------------------------
    // ESLINT RULES
    // -----------------------------------------------------------------------------

    // possible errors -------------------------------------------------------------

    'no-cond-assign': 2,
    'no-console': 1,
    'no-constant-condition': 2,
    'no-control-regex': 2,
    'no-debugger': 2,
    'no-dupe-args': 2,
    'no-dupe-keys': 2,
    'no-duplicate-case': 2,
    'no-empty-character-class': 2,
    'no-empty': 2,
    'no-ex-assign': 2,
    'no-extra-boolean-cast': 2,
    'no-extra-parens': 2,
    'no-extra-semi': 2,
    'no-func-assign': 2,
    'no-inner-declarations': 2,
    'no-invalid-regexp': 2,
    'no-irregular-whitespace': 2,
    'no-negated-in-lhs': 2,
    'no-obj-calls': 2,
    'no-prototype-builtins': 0,
    'no-regex-spaces': 2,
    'no-sparse-arrays': 2,
    'no-unexpected-multiline': 2,
    'no-unreachable': 2,
    'no-unsafe-finally': 2,
    'use-isnan': 2,
    'valid-jsdoc': 0,
    'valid-typeof': 2,

    // best practices --------------------------------------------------------------

    'accessor-pairs': 0,
    'array-callback-return': 0,
    'block-scoped-var': 0,
    'complexity': 0,
    'consistent-return': 2,
    'curly': [2, 'all'],
    'default-case': 0,
    'dot-location': 0,
    'dot-notation': [2, { 'allowKeywords': true }],
    'eqeqeq': [2, 'smart'],
    'guard-for-in': 0,
    'no-alert': 2,
    'no-caller': 2,
    'no-case-declarations': 2,
    'no-div-regex': 0,
    'no-else-return': 0,
    'no-empty-function': 0,
    'no-empty-pattern': 2,
    'no-eq-null': 0,
    'no-eval': 2,
    'no-extend-native': 2,
    'no-extra-bind': 2,
    'no-extra-label': 0,
    'no-fallthrough': 2,
    'no-floating-decimal': 0,
    'no-implicit-coercion': 0,
    'no-implicit-globals': 0,
    'no-implied-eval': 2,
    'no-invalid-this': 0,
    'no-iterator': 2,
    'no-labels': 2,
    'no-lone-blocks': 2,
    'no-loop-func': 2,
    'no-magic-numbers': 0,
    'no-multi-spaces': 2,
    'no-multi-str': 2,
    'no-native-reassign': 2,
    'no-new': 2,
    'no-new-func': 2,
    'no-new-wrappers': 2,
    'no-octal': 2,
    'no-octal-escape': 2,
    'no-param-reassign': 0,
    'no-proto': 2,
    'no-redeclare': 2,
    'no-return-assign': 2,
    'no-script-url': 2,
    'no-self-assign': 2,
    'no-self-compare': 0,
    'no-sequences': 2,
    'no-throw-literal': 0,
    'no-unmodified-loop-condition': 0,
    'no-unused-expressions': 2,
    'no-unused-labels': 2,
    'no-useless-call': 0,
    'no-useless-concat': 0,
    'no-useless-escape': 0,
    'no-void': 0,
    'no-warning-comments': 0,
    'no-with': 2,
    'radix': 0,
    'vars-on-top': 0,
    'wrap-iife': 0,
    'yoda': [2, 'never'],

    // variables -------------------------------------------------------------------

    'init-declarations': 0,
    'no-catch-shadow': 0,
    'no-delete-var': 2,
    'no-label-var': 2,
    'no-restricted-globals': 0,
    'no-shadow': 2,
    'no-shadow-restricted-names': 2,
    'no-undef': 2,
    'no-undef-init': 2,
    'no-undefined': 0,
    'no-unused-vars': 2,
    'no-use-before-define': 2,

    // nodejs ----------------------------------------------------------------------

    'callback-return': 0,
    'global-require': 0,
    'handle-callback-err': 0,
    'no-mixed-requires': 0,
    'no-new-require': 0,
    'no-path-concat': 0,
    'no-process-env': 0,
    'no-process-exit': 2,
    'no-restricted-modules': 0,
    'no-sync': 0,

    // stylistic issues ------------------------------------------------------------

    'array-bracket-spacing': 0,
    'block-spacing': 0,
    'brace-style': 0,
    'camelcase': 0,
    'comma-dangle': 0,
    'comma-spacing': 2,
    'comma-style': 0,
    'computed-property-spacing': 0,
    'consistent-this': 0,
    'eol-last': 2,
    'func-names': 0,
    'func-style': 0,
    'id-blacklist': 0,
    'id-length': 0,
    'id-match': 0,
    'indent': [2, 2, { 'SwitchCase': 1 }],
    'jsx-quotes': 2,
    'key-spacing': [2, { 'beforeColon': false, 'afterColon': true }],
    'keyword-spacing': 2,
    'linebreak-style': 0,
    'lines-around-comment': 0,
    'max-depth': 0,
    'max-len': 0,
    'max-lines': 0,
    'max-nested-callbacks': 0,
    'max-params': 0,
    'max-statements': 0,
    'max-statements-per-line': 0,
    'multiline-ternary': 0,
    'new-cap': 0,
    'new-parens': 2,
    'newline-after-var': 0,
    'newline-before-return': 0,
    'newline-per-chained-call': 0,
    'no-array-constructor': 2,
    'no-bitwise': 0,
    'no-continue': 0,
    'no-inline-comments': 0,
    'no-lonely-if': 0,
    'no-mixed-operators': 0,
    'no-mixed-spaces-and-tabs': [2, false],
    'no-multiple-empty-lines': 0,
    'no-negated-condition': 0,
    'no-nested-ternary': 0,
    'no-new-object': 2,
    'no-plusplus': 0,
    'no-restricted-syntax': 0,
    'no-spaced-fun': 0,
    'no-spaced-func': 2,
    'no-tabs': 0,
    'no-ternary': 0,
    'no-trailing-spaces': 2,
    'no-underscore-dangle': 0,
    'no-unneeded-ternary': 0,
    'no-whitespace-before-property': 0,
    'object-curly-newline': 0,
    'object-curly-spacing': 0,
    'object-property-newline- one-var-declaration-per-line': 0,
    'one-var': 0,
    'operator-assignment': 0,
    'operator-linebreak': 0,
    'padded-blocks': 0,
    'quote-props': 0,
    'quotes': [2, 'single', 'avoid-escape'],
    'require-jsdoc': 0,
    'semi': 2,
    'semi-spacing': [2, {'before': false, 'after': true}],
    'sort-vars': 0,
    'space-before-blocks': 0,
    'space-before-function-paren': 0,
    'space-in-parens': 0,
    'space-infix-ops': 2,
    'space-unary-ops': [2, {'words': true, 'nonwords': false}],
    'spaced-comment': 0,
    'unicode-bom': 0,
    'wrap-regex': 0,

    // -----------------------------------------------------------------------------
    // PLUGINS
    // -----------------------------------------------------------------------------

    // react plugin ----------------------------------------------------------------

    'react/jsx-no-undef': 2,
    'react/jsx-uses-vars': 2,
    'react/react-in-jsx-scope': 2,
    'react/jsx-uses-react': 2,

  }
};
